name: NoDroppingOffline
main: com.minetexas.nodroppingoffline.NoDroppingOffline
version: 0.4
author: ataranlen
description: Prevent players from duping via dropping items and dcing.
depend: [ProtocolLib]
